---
global:
    # add options to allow either in-memory or disk-based processing
    out_folder: "."  # default is current working directory
    store_per_obs: true
    logging:
        level: info

observations:
    data_store: $GAMMAPY_DATA/cta-1dc/index/gps/
    ids: 110380, 111140, 111159
    conesearch:
        ra:
        dec:
        radius:
        energy_min:
        energy_max:
        time_min:
        time_max:

grid:
    spatial: center, width, binsz
    energy: min, max, nbins
    time: min, max
    # PSF RAD and EDISP MIGRA not exposed for now
    # Per-obs energy_safe and roi_max ?

model:
    # Model configuration will mostly be designed in different PIG
    sources:
        source_1:
            spectrum: powerlaw
            spatial: shell
        diffuse: gal_diffuse.fits
    background:
        IRF

analysis:
    reduce:
        type: {"1D", "3D"}
        stacked: {true, false}
        background: {"irf", "reflected", "ring"}
        roi: max_offset
        exclusion: exclusion.fits
    fit:
        energy_min, energy_max
